### ISSUE TITLE
Compaginación de resultados

### ISSUE THREAD

**Issue by LiliReina** [Nearsoft/questions#137]
No aparecen en NEWEST ni al hacer SEARCH algunos posts. 
EJEMPLOS:

http://www.nuuk.me/question/19#a-19?utm_source=Lili&utm_medium=Facebook&utm_campaign=19RO2016

http://www.nuuk.me/question/18?utm_source=Clau&utm_medium=Twitter&utm_campaign=18RO2016

**Comment by wdonet** [comment]
I think this is related to Elastic Search not saving data correctly or us not handling the way we save data in the right way.
The NEWEST case might be related to the sorting type (probably fixed in previous commits - pls verify)
The SEARCH case might be related to Elastic Search as mentioned above or initial data not going through the save process of a question.
We can talk about it whenever you are available

**Comment by wdonet** [comment]
unassigning @wombstrat , @jd-hernandez any update?

**Comment by wdonet** [comment]
closing since the code is reindexing again at starting the app with Jorge's change at [157b893](https://github.com/Nearsoft/questions/commit/157b893da5431fca78523e2300b911f70fb93550)
