### ISSUE TITLE
Comments in UI

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#74]
Acceptance Criteria:

1. Show a link below the question in order to add a comment
2. Show a link below the answer in order to add a comment
3. Show list of comments on each section ordered by less recent first and showing: content, owner and date
4. If there's more than 3 comments in list, the list should be hidden but with an option to unfold/show the rest at the same page when user need it.

**Comment by mmedina-nearsoft** [comment]
![comments-hidden](https://cloud.githubusercontent.com/assets/7750508/15376866/9a37e53c-1d0c-11e6-9f0a-d219a9860728.jpg)
![question2](https://cloud.githubusercontent.com/assets/7750508/15376865/9a36dca0-1d0c-11e6-9274-df05b4521d72.jpg)

**Comment by jmsalcido** [comment]
Acceptance Criteria:

- [ ] Show a link below the question in order to add a comment
- [ ] Show a link below the answer in order to add a comment
- [ ] Show list of comments on each section ordered by less recent first and showing: content, owner and date
- [ ] If there's more than 3 comments in list, the list should be hidden but with an option to unfold/show the rest at the same page when user need it.

**Comment by jmsalcido** [comment]
@imarban there should appear a simple text input to add a comment and parse markdown?

**Comment by jmsalcido** [comment]
this is already on origin/hackday

**Comment by wdonet** [comment]
"If there's more than 3 comments in list, the list should be hidden but with an option to unfold/show the rest at the same page when user need it."
This is missing but for now we have the functionality of hide/show all, so let's keep it in that way for now
