### ISSUE TITLE
After commenting, the page should anchor down to the comment.

### ISSUE THREAD

**Issue by gsancheznearsoft** [Nearsoft/questions#89]
Currently, after commenting the page isn't scrolling down to the comment which was just posted.

This wasn't specified initially, so it's a nice-to-have/missed requirement.

![image](https://cloud.githubusercontent.com/assets/2767847/15719991/0b36881a-27f8-11e6-8ca8-58d66c2ec119.png)

**Comment by vanchondo** [comment]
I added id tag for Questions comments, Answers comments and answers because I notice that the page wasn't scrolling down after making a answer.

For question comments I used the prefix 'qc-' followed by the comment id i.e. qc-5
For answer comments I used the prefix 'ac-' followed by the answer comment id i.e. ac-7
For answers I used the prefix 'a-' followed by the answer id i.e. a-3

Using html bookmarks when the 5th comment for question 9th has been commented, url will be /question/9#qc-5
