### ISSUE TITLE
User can submit empty comments.

### ISSUE THREAD

**Issue by gsancheznearsoft** [Nearsoft/questions#91]
Currently, users can submit empty comments which add no value to discussion.

![image](https://cloud.githubusercontent.com/assets/2767847/15720497/5398f3b6-27fa-11e6-991b-a5519294f405.png)

**Comment by wdonet** [comment]
I saw a weird behavior on CommentsController 
- saveAnswerComment()  mapped to "/answer/{id}" and  "/answer"
- saveQuestionComment() mapped to "/question/{id}" and  "/question"

However {id} is not mapped to any argument inside the method.  We should recover ids from URL in order to avoid unnecessary calls to the DB for getting ids of other related objects

Fixed  Using a single service for comments, no matter if it is going to be added to questions or answers and we use the corresponding IDs on the URLs directly
